#!/usr/bin/env bash
#
# Orbital configuration inventory.
#
# Emits a deterministic description of what a host is ACTUALLY running —
# services, proxy, TLS, kernel-facing config, code refs on every fleet member,
# and the NAMES (never the values) of the secrets it holds.
#
# Two uses:
#   1. Baseline. Capture prod's truth before the environment split so the new
#      hosts can be built to match, rather than to a document that drifted.
#   2. Drift detection. `--check <baseline.md>` diffs today's reality against a
#      stored baseline. CLAUDE.md's #1 recurring failure is "ops deployment is
#      3 places, not 1" — a fix merged, deployed to the master, and forgotten
#      on a worker. A diff catches that the morning after, not at the next
#      workshop.
#
# Deterministic by construction: everything is sorted, and nothing that changes
# on its own between runs (timestamps, PIDs, uptimes, memory) is included.
# Otherwise every run would diff against every other run and the signal dies.
#
# Usage:
#   orbital-inventory.sh                      # print inventory to stdout
#   orbital-inventory.sh --check baseline.md  # diff against a baseline
#
set -uo pipefail

WORKERS="${ORBITAL_INVENTORY_WORKERS:-autonomous-enablements-worker autonomous-enablements-worker-2}"
OPS_ENV="${ORBITAL_OPS_ENV_FILE:-/home/ops/.env}"
OPS_CHECKOUT="${ORBITAL_CHECKOUT:-/home/ops/enablement-framework/codespaces-framework}"
SSH_AS="${ORBITAL_INVENTORY_SSH_USER:-ubuntu}"

as_ssh() { sudo -u "$SSH_AS" timeout 25 ssh -o BatchMode=yes -o ConnectTimeout=8 "$@" 2>/dev/null; }
sec()    { printf '\n## %s\n\n' "$1"; }

# `systemctl is-active` PRINTS the state and exits non-zero for anything that
# is not active, so the obvious `is-active X || echo absent` emits two lines.
# Distinguish "unit exists but is stopped" from "unit is not installed".
oneagent_state() {
    local s; s="$(systemctl is-active oneagent 2>/dev/null || true)"
    [ -n "$s" ] && echo "$s" || echo absent
}
oneagent_mode() {
    local m
    m="$(grep -h Monitoring-mode /var/lib/dynatrace/oneagent/agent/config/monitoringmode.conf 2>/dev/null | cut -d= -f2)"
    [ -n "$m" ] && echo "$m" || echo none
}

inventory() {
    echo "# Orbital configuration inventory"
    echo
    echo "Generated by \`tools/inventory/orbital-inventory.sh\`. Values of secrets are"
    echo "never included — only their names. Deterministic: safe to diff run-to-run."
    echo
    echo "- host: \`$(hostname)\`"
    echo "- environment: \`${ORBITAL_ENV:-prod}\`"

    sec "Systemd units (enabled state)"
    echo '```'
    systemctl list-unit-files --no-pager --no-legend 2>/dev/null \
        | grep -E '^(ops-|oauth2-proxy|orbital-|redis-server|nginx)' \
        | awk '{printf "%-40s %s\n", $1, $2}' | sort
    echo '```'

    sec "Services expected to be running"
    echo '```'
    for u in nginx redis-server oauth2-proxy ops-dashboard ops-webhook ops-worker; do
        printf '%-20s %s\n' "$u" "$(systemctl is-active "$u" 2>/dev/null)"
    done
    echo '```'

    sec "Listening sockets (service-owned)"
    # Ports only, with the owning program. Excludes ephemeral/container ports,
    # which churn constantly and would make every diff noisy.
    # -p is required for the process column; without it ss prints no users:(())
    # and every line silently drops out of the filter below.
    echo '```'
    ss -tlnpH 2>/dev/null \
        | awk '{split($4,a,":"); port=a[length(a)];
                match($0,/users:\(\("([^"]+)"/,m);
                if (port+0 < 32000 && m[1] != "") printf "%-8s %s\n", port, m[1]}' \
        | sort -n -u
    echo '```'

    # -R, not -r: sites-enabled holds symlinks into sites-available, and grep -r
    # does not follow them. -r here silently reports an nginx with no server names.
    sec "nginx server names"
    echo '```'
    grep -RhoP '^\s*server_name\s+\K[^;]+' /etc/nginx/sites-enabled/ 2>/dev/null \
        | tr -s ' ' '\n' | sed '/^$/d' | sort -u
    echo '```'
    # [^#]* stops the match at a comment. The live config carries the trailing
    # note "# http2 removed: ..." explaining why it must stay off — matching
    # that would report http2 as ENABLED on a host where it is correctly absent.
    echo "http2 directives on listeners (must be **0** — nginx 1.24 lacks RFC 8441, breaks WebSocket):"
    echo '```'
    grep -RhoP '^\s*listen\s+[^#]*\bhttp2\b' /etc/nginx/sites-enabled/ 2>/dev/null | wc -l
    echo '```'

    sec "TLS certificates"
    echo '```'
    for d in /etc/letsencrypt/live/*/; do
        [ -f "${d}cert.pem" ] || continue
        printf '%-55s expires %s\n' "$(basename "$d")" \
            "$(openssl x509 -enddate -noout -in "${d}cert.pem" 2>/dev/null | cut -d= -f2)"
    done | sort
    echo '```'
    echo "certbot authenticator:"
    echo '```'
    grep -hE '^(authenticator|manual_auth_hook)' /etc/letsencrypt/renewal/*.conf 2>/dev/null | sort -u
    echo '```'

    sec "SSH"
    echo '```'
    printf 'port(s):              %s\n' \
        "$(sshd -T 2>/dev/null | awk '/^port /{print $2}' | paste -sd, || echo unknown)"
    printf 'passwordauthentication: %s\n' "$(sshd -T 2>/dev/null | awk '/^passwordauthentication /{print $2}')"
    printf 'permitrootlogin:      %s\n' "$(sshd -T 2>/dev/null | awk '/^permitrootlogin /{print $2}')"
    echo '```'

    sec "Redis"
    echo '```'
    local pw; pw="$(grep -oP '^REDIS_PASSWORD=\K.*' "$OPS_ENV" 2>/dev/null)"
    if [ -n "$pw" ]; then
        local -a r=(redis-cli -a "$pw" --no-auth-warning)
        for k in appendonly appendfsync save maxmemory maxmemory-policy bind protected-mode; do
            printf '%-20s %s\n' "$k" "$("${r[@]}" config get "$k" 2>/dev/null | tail -1)"
        done
        printf '%-20s %s\n' "auth-passwords" \
            "$("${r[@]}" acl getuser default 2>/dev/null | grep -cE '^[0-9a-f]{64}$')"
    else
        echo "REDIS_PASSWORD not readable"
    fi
    echo '```'

    sec "Secret names held in ${OPS_ENV}"
    echo "Count and names only. A new name appearing here without a corresponding"
    echo "change in git is worth a question."
    echo '```'
    grep -oE '^[A-Z_0-9]+=' "$OPS_ENV" 2>/dev/null | tr -d '=' | sort
    echo '```'

    sec "Pinned versions"
    echo '```'
    printf '%-20s %s\n' "APP_DEPLOY_REF" "$(grep -oP '^APP_DEPLOY_REF=\K.*' "$OPS_ENV" 2>/dev/null)"
    printf '%-20s %s\n' "CONTROL_LOOP_APPLY" "$(grep -oP '^CONTROL_LOOP_APPLY=\K.*' "$OPS_ENV" 2>/dev/null)"
    printf '%-20s %s\n' "WORKER_CODE_BRANCH" "$(grep -oP '^WORKER_CODE_BRANCH=\K.*' "$OPS_ENV" 2>/dev/null || echo '(unset → main)')"
    echo '```'

    sec "Fleet code refs"
    echo "All hosts must report the same ref. A divergence here IS the drift that"
    echo "breaks a training the night after a partial deploy."
    echo '```'
    # `sudo -u ops`, not bare `sudo`: the checkout is owned by ops, and git run
    # as root refuses it with "detected dubious ownership" — which reads as an
    # unreachable host rather than the permissions problem it is.
    printf '%-42s %s\n' "master ($(hostname))" \
        "$(sudo -u ops git -C "$OPS_CHECKOUT" rev-parse --short HEAD 2>/dev/null || echo 'no checkout')"
    local w ref
    for w in $WORKERS; do
        ref="$(as_ssh "$w" "sudo -n -u ops git -C $OPS_CHECKOUT rev-parse --short HEAD")"
        printf '%-42s %s\n' "$w" "${ref:-unreachable}"
    done
    echo '```'

    sec "OneAgent"
    echo "Prod workers must be **infra-only**: host and container metrics plus"
    echo "container logs, with no injection into learner containers."
    echo '```'
    printf '%-42s %-10s %s\n' "HOST" "SERVICE" "MODE"
    printf '%-42s %-10s %s\n' "master ($(hostname))" \
        "$(oneagent_state)" "$(oneagent_mode)"
    for w in $WORKERS; do
        # One round trip returning "<state> <mode>", so a slow or unreachable
        # worker cannot produce a half-filled row from two separate calls.
        local row; row="$(as_ssh "$w" \
            'printf "%s %s\n" \
               "$(systemctl is-active oneagent 2>/dev/null || true)" \
               "$(sudo -n grep -h Monitoring-mode /var/lib/dynatrace/oneagent/agent/config/monitoringmode.conf 2>/dev/null | cut -d= -f2 || true)"')"
        printf '%-42s %-10s %s\n' "$w" \
            "$(echo "$row" | awk '{print ($1=="") ? "unreachable" : $1}')" \
            "$(echo "$row" | awk '{print ($2=="") ? "none" : $2}')"
    done
    echo '```'

    sec "Backups"
    echo '```'
    printf '%-24s %s\n' "backup timer" "$(systemctl is-enabled orbital-backup.timer 2>/dev/null || echo absent)"
    printf '%-24s %s\n' "drill timer"  "$(systemctl is-enabled orbital-restore-drill.timer 2>/dev/null || echo absent)"
    printf '%-24s %s\n' "offsite S3" \
        "$(grep -oP '^ORBITAL_BACKUP_S3_URI=\K.*' /etc/default/orbital-backup 2>/dev/null || echo 'NOT CONFIGURED — local only')"
    printf '%-24s %s\n' "local snapshots" \
        "$(sudo find /var/backups/orbital -mindepth 1 -maxdepth 1 -type d -regextype posix-extended -regex '.*/[0-9]{8}T[0-9]{6}Z' 2>/dev/null | wc -l)"
    echo '```'
}

if [ "${1:-}" = "--check" ]; then
    BASELINE="${2:?usage: --check <baseline.md>}"
    [ -f "$BASELINE" ] || { echo "baseline not found: $BASELINE" >&2; exit 2; }
    TMP="$(mktemp)"; trap 'rm -f "$TMP"' EXIT
    inventory > "$TMP"
    # Ignore the generated-host preamble; compare the substance.
    if diff -u <(sed '1,6d' "$BASELINE") <(sed '1,6d' "$TMP"); then
        echo "inventory: no drift from $(basename "$BASELINE")"
        exit 0
    fi
    echo "inventory: DRIFT detected against $(basename "$BASELINE")" >&2
    exit 1
fi

inventory
