"""sync push-update — Bump framework version across repos using local-first workflow.

Flow per repo:
  1. Ensure cloned locally (clone if missing)
  2. git checkout main && git pull
  3. Create branch sync/framework-<version>
  4. Update source_framework.sh version pin
  5. Run migrate to update templates (Makefile, source_framework.sh structure)
  6. Commit, push, create PR with auto-merge
  7. On failure at any step, leave branch in place for manual intervention
"""

import json
import sys

from sync.core.repos import load_repos, filter_sync_targets
from sync.core.version import extract_framework_version
from sync.core import local_git
from sync.commands.migrate import SOURCE_FRAMEWORK_TEMPLATE, THIN_MAKEFILE

SYNC_BRANCH_PREFIX = "sync/framework-"
SOURCE_FW_PATH = ".devcontainer/util/source_framework.sh"


def _update_repo(repo_entry, target: str, dry_run: bool, force: bool) -> dict:
    """Process a single repo. Returns a result dict."""
    owner, name = repo_entry.owner, repo_entry.repo_name
    result = {"repo": repo_entry.repo, "status": "skipped", "message": ""}

    # 1. Ensure cloned
    try:
        path = local_git.ensure_cloned(owner, name)
    except local_git.GitError as e:
        result["status"] = "error"
        result["message"] = f"clone failed: {e.message}"
        return result

    # 2. Pull latest main
    pull = local_git.pull_main(path)
    if not pull.success:
        result["status"] = "error"
        result["message"] = pull.message
        result["needs_manual"] = True
        return result

    # 3. Check current version
    sf_path = path / SOURCE_FW_PATH
    if not sf_path.exists():
        result["message"] = "not migrated (no source_framework.sh)"
        return result

    content = sf_path.read_text()
    try:
        current = extract_framework_version(content)
    except ValueError:
        result["message"] = "not migrated (no FRAMEWORK_VERSION pin)"
        return result

    if current == target and not force:
        result["message"] = f"already at {target}"
        return result

    if dry_run:
        result["status"] = "would-update"
        result["message"] = f"{current} → {target}"
        return result

    # 4. Create branch
    branch_name = f"{SYNC_BRANCH_PREFIX}{target}"
    branch = local_git.create_branch(path, branch_name)
    if not branch.success:
        result["status"] = "skipped"
        result["message"] = branch.message
        return result

    # 5. Update source_framework.sh — new version pin + latest template
    sf_path.write_text(SOURCE_FRAMEWORK_TEMPLATE % target)

    # 6. Update thin Makefile to latest template
    makefile_path = path / ".devcontainer/Makefile"
    if makefile_path.exists():
        makefile_path.write_text(THIN_MAKEFILE)

    # 7. Commit
    commit_msg = f"chore: sync framework @ {target}"
    commit = local_git.commit(path, commit_msg)
    if "no changes" in commit.message:
        result["message"] = f"already at {target} (templates up to date)"
        return result

    # 8. Push
    push = local_git.push(path, branch_name)
    if not push.success:
        result["status"] = "error"
        result["message"] = push.message
        result["needs_manual"] = True
        return result

    # 9. Create PR
    default_branch = local_git.get_default_branch(path)
    pr_body = (
        f"## Sync update\n\n"
        f"Bumps `FRAMEWORK_VERSION` from `{current}` to `{target}`.\n"
        f"Updates `source_framework.sh` and `Makefile` templates.\n\n"
        f"Auto-generated by `sync push-update`."
    )
    pr = local_git.create_pr(owner, name, path, commit_msg, pr_body, base=default_branch)
    if not pr.success:
        result["status"] = "error"
        result["message"] = pr.message
        result["needs_manual"] = True
        return result

    # 10. Enable auto-merge (best-effort)
    local_git.enable_auto_merge(owner, name, pr.message)

    result["status"] = "created"
    result["url"] = pr.message
    result["message"] = f"{current} → {target}"
    return result


def run(args):
    target = args.framework_version
    dry_run = args.dry_run
    force = args.force
    json_out = args.json_output

    repos = filter_sync_targets(load_repos())
    if not repos:
        print("No sync-managed active repos found.")
        return

    print(f"{'[DRY RUN] ' if dry_run else ''}Syncing {len(repos)} repos to framework {target}\n")

    results = []
    manual_needed = []

    for repo_entry in repos:
        print(f"── {repo_entry.repo} ──")
        result = _update_repo(repo_entry, target, dry_run, force)
        results.append(result)

        status = result["status"]
        msg = result["message"]

        if status == "created":
            print(f"  ✓ PR created: {result.get('url', '')}")
            print(f"    {msg}")
        elif status == "would-update":
            print(f"  ~ {msg}")
        elif status == "error":
            print(f"  ✗ {msg}")
            if result.get("needs_manual"):
                manual_needed.append(repo_entry.repo)
        else:
            print(f"  - {msg}")
        print()

    # Summary
    if json_out:
        print(json.dumps({"target_version": target, "repos": results}, indent=2))
    else:
        created = sum(1 for r in results if r["status"] == "created")
        skipped = sum(1 for r in results if r["status"] == "skipped")
        errors = sum(1 for r in results if r["status"] == "error")
        would = sum(1 for r in results if r["status"] == "would-update")

        if dry_run:
            print(f"Would update {would} repos, {skipped} already up to date")
        else:
            print(f"Created {created} PRs, {skipped} skipped, {errors} errors")

        if manual_needed:
            print(f"\n⚠ Manual intervention needed for:")
            for repo in manual_needed:
                path = local_git.get_repo_path(repo.split("/")[-1])
                print(f"  cd {path}")
