"""sync push-update — Open PRs to bump framework version across repos."""

import json
import sys

from sync.core.repos import load_repos, filter_sync_targets
from sync.core.github_api import (
    check_rate_limit,
    get_file_content,
    get_file_sha,
    get_default_branch,
    get_branch_sha,
    create_branch,
    update_file,
    create_pr,
    enable_auto_merge,
    branch_exists,
    GHAPIError,
)
from sync.core.version import extract_framework_version, update_framework_version

SYNC_BRANCH_PREFIX = "sync/framework-"
SOURCE_FW_PATH = ".devcontainer/util/source_framework.sh"


def run(args):
    target = args.framework_version
    dry_run = args.dry_run
    force = args.force
    json_out = args.json_output

    repos = filter_sync_targets(load_repos())
    if not repos:
        print("No sync-managed active repos found.")
        return

    # Pre-flight: check token
    if not dry_run:
        try:
            rate = check_rate_limit()
            remaining = rate.get("rate", {}).get("remaining", 0)
            if remaining < len(repos) * 5:
                print(
                    f"Warning: only {remaining} API calls remaining. "
                    f"Need ~{len(repos) * 5} for {len(repos)} repos.",
                    file=sys.stderr,
                )
        except GHAPIError as e:
            print(f"Token validation failed: {e.message}", file=sys.stderr)
            sys.exit(1)

    results = []
    for repo_entry in repos:
        owner, name = repo_entry.owner, repo_entry.repo_name
        result = {"repo": repo_entry.repo, "status": "skipped", "message": ""}

        try:
            # Get current version
            content = get_file_content(owner, name, SOURCE_FW_PATH)
            try:
                current = extract_framework_version(content)
            except ValueError:
                result["status"] = "skipped"
                result["message"] = "not migrated (no FRAMEWORK_VERSION line)"
                results.append(result)
                if not json_out:
                    print(f"  - {repo_entry.repo}: not migrated yet")
                continue

            if current == target:
                result["message"] = f"already at {target}"
                results.append(result)
                if not json_out:
                    print(f"  - {repo_entry.repo}: already at {target}")
                continue

            # Compute new content
            new_content = update_framework_version(content, target)

            if dry_run:
                result["status"] = "would-update"
                result["message"] = f"{current} -> {target}"
                results.append(result)
                if not json_out:
                    print(f"  ~ {repo_entry.repo}: {current} -> {target}")
                continue

            # Create branch and PR
            branch_name = f"{SYNC_BRANCH_PREFIX}{target}"

            if branch_exists(owner, name, branch_name):
                result["message"] = f"branch {branch_name} already exists (PR may be open)"
                results.append(result)
                if not json_out:
                    print(f"  - {repo_entry.repo}: branch already exists")
                continue

            default_branch = get_default_branch(owner, name)
            base_sha = get_branch_sha(owner, name, default_branch)
            create_branch(owner, name, branch_name, base_sha)

            # Update source_framework.sh
            file_sha = get_file_sha(owner, name, SOURCE_FW_PATH, ref=branch_name)
            update_file(
                owner,
                name,
                SOURCE_FW_PATH,
                new_content,
                f"chore: sync framework @ {target}",
                branch_name,
                file_sha,
            )

            # Create PR
            pr_data = create_pr(
                owner,
                name,
                title=f"chore: sync framework @ {target}",
                body=(
                    f"## Sync update\n\n"
                    f"Bumps `FRAMEWORK_VERSION` from `{current}` to `{target}`.\n\n"
                    f"Auto-generated by `sync push-update`."
                ),
                head=branch_name,
                base=default_branch,
            )

            pr_url = pr_data.get("html_url", "")
            pr_number = pr_data.get("number", 0)

            # Try to enable auto-merge
            enable_auto_merge(owner, name, pr_number)

            result["status"] = "created"
            result["url"] = pr_url
            result["number"] = pr_number
            result["message"] = f"{current} -> {target}"
            results.append(result)

            if not json_out:
                print(f"  + {repo_entry.repo}: PR #{pr_number} ({current} -> {target})")
                print(f"    {pr_url}")

        except GHAPIError as e:
            result["status"] = "error"
            result["message"] = str(e.message)
            results.append(result)
            if not json_out:
                print(f"  x {repo_entry.repo}: {e.message}", file=sys.stderr)

    # Summary
    if json_out:
        print(json.dumps({"target_version": target, "repos": results}, indent=2))
    else:
        created = sum(1 for r in results if r["status"] == "created")
        skipped = sum(1 for r in results if r["status"] == "skipped")
        errors = sum(1 for r in results if r["status"] == "error")
        prefix = "Would create" if dry_run else "Created"
        would = sum(1 for r in results if r["status"] == "would-update")
        if dry_run:
            print(f"\n{prefix} {would} PRs, {skipped} already up to date")
        else:
            print(f"\n{prefix} {created} PRs, {skipped} skipped, {errors} errors")
