"""sync push-update — Full sync workflow: pull, branch, migrate, push, PR.

Flow per repo:
  1. Ensure cloned locally (clone if missing)
  2. git checkout main && git pull
  3. Create branch sync/framework-<version>
  4. Run full migration (Category A cleanup, templates, mkdocs, .env, etc.)
  5. Commit all changes
  6. Push branch
  7. Create PR (optionally with auto-merge)
  8. On failure at any step, leave branch in place for manual intervention
"""

import json
import sys
from pathlib import Path

from sync.core.repos import load_repos, filter_sync_targets
from sync.core.version import extract_framework_version
from sync.core import local_git
from sync.commands.migrate import _migrate_repo, _resolve_repo_path

SYNC_BRANCH_PREFIX = "sync/framework-"
SOURCE_FW_PATH = ".devcontainer/util/source_framework.sh"


def _update_repo(repo_entry, target: str, dry_run: bool, force: bool, auto_merge: bool) -> dict:
    """Process a single repo. Returns a result dict."""
    owner, name = repo_entry.owner, repo_entry.repo_name
    result = {"repo": repo_entry.repo, "status": "skipped", "message": ""}

    # 1. Ensure cloned
    try:
        path = local_git.ensure_cloned(owner, name)
    except local_git.GitError as e:
        result["status"] = "error"
        result["message"] = f"clone failed: {e.message}"
        return result

    # 2. Pull latest main
    print(f"  pulling main...")
    pull = local_git.pull_main(path)
    if not pull.success:
        result["status"] = "error"
        result["message"] = pull.message
        result["needs_manual"] = True
        return result

    # 3. Check current version (if source_framework.sh exists)
    sf_path = path / SOURCE_FW_PATH
    current = None
    if sf_path.exists():
        content = sf_path.read_text()
        try:
            current = extract_framework_version(content)
        except ValueError:
            pass

    if current == target and not force:
        # Check if templates are up to date too
        from sync.commands.migrate import SOURCE_FRAMEWORK_TEMPLATE, THIN_MAKEFILE
        sf_ok = sf_path.exists() and sf_path.read_text() == SOURCE_FRAMEWORK_TEMPLATE % target
        mf_ok = (path / ".devcontainer/Makefile").exists() and (path / ".devcontainer/Makefile").read_text() == THIN_MAKEFILE
        if sf_ok and mf_ok:
            result["message"] = f"already at {target}"
            return result

    if dry_run:
        if current:
            result["status"] = "would-update"
            result["message"] = f"{current} → {target}"
        else:
            result["status"] = "would-update"
            result["message"] = f"not yet migrated → {target}"
        return result

    # 4. Create branch
    branch_name = f"{SYNC_BRANCH_PREFIX}{target}"
    branch = local_git.create_branch(path, branch_name)
    if not branch.success:
        result["status"] = "skipped"
        result["message"] = branch.message
        return result

    # 5. Run full migration
    print(f"  migrating...")
    try:
        status = _migrate_repo(repo_entry, path, target, dry_run=False)
    except Exception as e:
        result["status"] = "error"
        result["message"] = f"migration failed: {e}"
        result["needs_manual"] = True
        return result

    # Force version pin to target (migrate preserves existing pin, we want to bump it)
    from sync.commands.migrate import SOURCE_FRAMEWORK_TEMPLATE
    sf_path.write_text(SOURCE_FRAMEWORK_TEMPLATE % target)

    # 6. Commit
    if not local_git.has_changes(path):
        # No changes — checkout back to main
        default_branch = local_git.get_default_branch(path)
        local_git._run_git(["checkout", default_branch], path)
        local_git._run_git(["branch", "-D", branch_name], path, check=False)
        result["message"] = f"already at {target} (no changes)"
        return result

    commit_msg = f"chore: sync framework @ {target}"
    local_git.commit(path, commit_msg)

    # 7. Push
    print(f"  pushing...")
    push = local_git.push(path, branch_name)
    if not push.success:
        result["status"] = "error"
        result["message"] = push.message
        result["needs_manual"] = True
        return result

    # 8. Create PR
    default_branch = local_git.get_default_branch(path)
    changes = []
    if current and current != target:
        changes.append(f"Bumps `FRAMEWORK_VERSION` from `{current}` to `{target}`.")
    elif not current:
        changes.append(f"Initial migration to versioned pull model at `{target}`.")
    changes.append("Updates templates (`source_framework.sh`, `Makefile`).")
    changes.append("Removes framework-owned files (Category A) — now pulled from cache.")

    pr_body = (
        f"## Sync update\n\n"
        + "\n".join(f"- {c}" for c in changes)
        + f"\n\nAuto-generated by `sync push-update`."
    )
    pr = local_git.create_pr(owner, name, path, commit_msg, pr_body, base=default_branch)
    if not pr.success:
        result["status"] = "error"
        result["message"] = pr.message
        result["needs_manual"] = True
        return result

    # 9. Enable auto-merge (only if requested)
    if auto_merge:
        local_git.enable_auto_merge(owner, name, pr.message)

    result["status"] = "created"
    result["url"] = pr.message
    result["message"] = f"{current or 'new'} → {target}"
    return result


def run(args):
    target = args.framework_version
    dry_run = args.dry_run
    force = args.force
    auto_merge = args.auto_merge
    json_out = args.json_output
    target_repo = getattr(args, "repo", None)

    repos = load_repos()
    if target_repo:
        repos = [r for r in repos if r.repo_name == target_repo or r.name == target_repo
                 or r.repo == target_repo]
        if not repos:
            print(f"x '{target_repo}' not found in repos.yaml", file=sys.stderr)
            sys.exit(1)
    else:
        repos = filter_sync_targets(repos)

    if not repos:
        print("No sync-managed active repos found.")
        return

    print(f"{'[DRY RUN] ' if dry_run else ''}Syncing {len(repos)} repos to framework {target}\n")

    results = []
    manual_needed = []

    for repo_entry in repos:
        print(f"── {repo_entry.repo} ──")
        result = _update_repo(repo_entry, target, dry_run, force, auto_merge)
        results.append(result)

        status = result["status"]
        msg = result["message"]

        if status == "created":
            print(f"  🚀 PR created: {result.get('url', '')}")
            print(f"    {msg}")
        elif status == "would-update":
            print(f"  ⏳ {msg}")
        elif status == "error":
            print(f"  ❌ {msg}")
            if result.get("needs_manual"):
                manual_needed.append(repo_entry.repo)
        else:
            print(f"  ⏭️  {msg}")
        print()

    # Summary
    if json_out:
        print(json.dumps({"target_version": target, "repos": results}, indent=2))
    else:
        created = sum(1 for r in results if r["status"] == "created")
        skipped = sum(1 for r in results if r["status"] == "skipped")
        errors = sum(1 for r in results if r["status"] == "error")
        would = sum(1 for r in results if r["status"] == "would-update")

        if dry_run:
            print(f"Would update {would} repos, {skipped} already up to date")
        else:
            print(f"Created {created} PRs, {skipped} skipped, {errors} errors")

        if manual_needed:
            print(f"\nManual intervention needed for:")
            for repo in manual_needed:
                path = local_git.get_repo_path(repo.split("/")[-1])
                print(f"  cd {path}")
