#!/bin/bash

VERSION="${VERSION:-"1.15"}"
NAMESPACE="${NAMESPACE:-"dapr-system"}"

helm upgrade --install dapr dapr \
    --repo https://dapr.github.io/helm-charts/ \
    --version="${VERSION}" \
    --atomic \
    --namespace "${NAMESPACE}" \
    --create-namespace \
    --set global.mtls.enabled=false \
    --wait
