name: Deploy Mkdocs to Gituhb Pages
run-name: ${{ github.event.head_commit.message }} - deploy GHPages
permissions:
  contents: write
on:
  push:
    branches:
      - docs/*
      - main
jobs:
  deploy:
    runs-on: ubuntu-24.04
    # No CI Test should run longer than 10 minutes.
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install mkdocs ghp-import
    - run: mkdocs build
    - run: ghp-import -n -p -f ./site