name: deploy mkdocs to github pages
run-name: ${{ github.event.head_commit.message }} - deploy github pages
on:
  push:
    branches:
      - main
      - docs/*
jobs:
  deploy:
    uses: dynatrace-wwse/codespaces-framework/.github/workflows/deploy-ghpages-reusable.yaml@main
    with:
      framework_version: "1.2.0"
