name: Deploy Mkdocs to Gituhb Pages
run-name: ${{ github.event.head_commit.message }}  - deploy GHPages
permissions:
  contents: write
on:
  push:
    branches:
      - docs/*
      - main
jobs:
  deploy:
    runs-on: ubuntu-24.04
    # No CI Test should run longer than 10 minutes.
    timeout-minutes: 10
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install Runme, MKDocs and deploy
      run: | 
        source .devcontainer/util/source_framework.sh
        installMkdocs
        #git fetch origin gh-pages
        #git checkout gh-pages || git checkout -b gh-pages
        #git pull origin gh-pages
        mkdocs build
        mkdocs gh-deploy
        #deployGhdocs
        # pip install --break-system-packages -r docs/requirements/requirements-mkdocs.txt
        # mkdocs gh-deploy --force