name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
permissions:
  contents: write
on: [push]
jobs:
  test-codespace:
    runs-on: ubuntu-22.04
    env:
      RepositoryName: "codespaces-synchronizer"
      DT_TENANT: ${{ secrets.DT_TENANT }}
      DT_OPERATOR_TOKEN: ${{ secrets.DT_OPERATOR_TOKEN }}
      DT_INGEST_TOKEN: ${{ secrets.DT_INGEST_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test Codespace (devcontainer) build and run commands
        uses: devcontainers/ci@v0.3
        run: |
            #chmod -R 755 .
            #cd .devcontainer 
            #cat <<EOF >> runlocal/.env
            #DT_TENANT=$DT_TENANT
            #DT_OPERATOR_TOKEN=$DT_OPERATOR_TOKEN
            #DT_INGEST_TOKEN=$DT_INGEST_TOKEN
            #EOF
            #echo "This is the env file" ; cat runlocal/.env
            #make test
            echo "------ some cmds... ------" ; pwd ; ls -las ; ls / ;
            echo "------ this is the tenant ${DT_TENANT} ------" 
            echo "------ I AM ------" ; whoami
            echo "------   Docker ps.   ------- " ; docker ps
            echo "env" ; env
            curl -v http://localhost:30100 | grep -q "todo" && echo "TODO App Running" || echo "TODO App Not Running"
        
