name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  test-codespace:
    runs-on: ubuntu-22.04
    env:
      RepositoryName: "codespaces-synchronizer"
      RepoName: "$GITHUB_REPOSITORY"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use secret
        run: echo "Tenant ${{ secrets.DT_TENANT }} with Tokens (Operator:${{ secrets.DT_OPERATOR_TOKEN }} Ingest:${{ secrets.DT_INGEST_TOKEN }} )"
      - name: Test Codespace (devcontainer) build and run multiple commands
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            echo "Curling the todo app running in the Codespace container"
            showOpenPorts
            echo "curling localhost"
            curl http://localhost:30100
            echo "curling hostname"
            curl http://$(hostname):30100
            echo "now doing grep"
            curl http://localhost:30100 | grep -q "todo" && echo "TODO App Running" || echo "TODO App Not Running" 
      - name: Build and run devcontainer using Makefile
        uses: devcontainers/ci@v0.3
        with:
          imageName: shinojosa/dt-enablement:v1.0
          runCmd: |
            pwd
            cd .devcontainer 
            make start
            echo "curling localhost"
            curl http://localhost:30100
            echo "curling hostname"
            curl http://$(hostname):30100
            echo "now doing grep"
            curl http://localhost:30100 | grep -q "todo" && echo "TODO App Running" || echo "TODO App Not Running" 