name: integration-tests
run-name: ${{ github.event.head_commit.message }} - PR integration test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: dynatrace-wwse/codespaces-framework/.github/workflows/integration-tests-reusable.yaml@main
    secrets: inherit
